### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by progval** [tstein/AndroSS#1]
Hello,

I just installed AndroSS, and it crashes when taking a snapshot (with shaking the phone) with toast and vibrate notification. But it does not crash with toast only.

HTC Desire with CyanogenMod 7.0.0-RC2.

ProgVal

**Comment by tstein** [comment]
This should be pretty easy to track down - I can only think of one spot this could be hiding. Just to be sure, if you've got adb installed, could I have the stack trace from `adb logcat`? If not, I can build you one with a null check in the suspicious place and see if that fixes your problem.
-Ted

**Comment by progval** [comment]
http://paste.pocoo.org/show/mx3Saoiii7xvmYUKz3NB/

**Comment by tstein** [comment]
I see it's a permissions problem - not what I expected. Dunno why it's been working on other devices, but I the dox say I had something in the wrong place. Try this build: http://dl.dropbox.com/u/9634624/AndroSS.apk

**Comment by progval** [comment]
It works.

Additionnally, I noticed I can't install this build if AndroSS is already installed (it says me "application not installed"). I have to uninstall it first, and then install it.

**Comment by progval** [comment]
I updated CyanogenMod to 7.0.0-RC4 yesterday

**Comment by tstein** [comment]
Excellent. I don't know why this didn't manifest on my devices, but I can believe that fix did the trick. Hopefully, that was it, and we're not looking a very strange bug in that specific build of CM or whatever. Don't worry about the uninstallation thing; it was probably just unhappy about installing a debug build on top of a release build. I'll push an update to the market within the hour.

Thanks for the report, and thanks for helping me track it down.
-Ted
