### ISSUE TITLE
su error on N900a Note 3

### ISSUE THREAD

**Issue by Firefishe** [tstein/AndroSS#12]
I have a rooted Samsung N900A running Lollipop 5.0. Using SuperSU. Busy box installed. 

I get contradictory errors. When Enable is checked, a popup appears saying AndroSS failed to initialize, then followed, intermittently, by another popup indicating su access has been granted.

**Comment by Fitefishe** [comment]
popular should read "popup"

**Comment by Fitefishe** [comment]
dating should read "indicating"

**Comment by tstein** [comment]
Since Android 4.0, screenshot functionality is built in, and AndroSS's methods do not work. You may need to look up instructions specific to your device, but the common case is that you can take a screenshot by holding the power button and the volume down button simultaneously for a few seconds.
