### ISSUE TITLE
Avoid capturing Superuser toast notification

### ISSUE THREAD

**Issue by dgw** [tstein/AndroSS#2]
Screen captures include the toast notification from Superuser indicating that AndroSS has been granted SU permissions. It should be possible to work around this with timing, at least, or ideally by excluding that component of the screen image.

**Comment by tstein** [comment]
Since that toast is obviously outside of AndroSS's control, it's sort of a race - it has to get into native code and slurp the pixels before Superuser's toast gets displayed. On my personal phone (a Nexus One - 1 GHz CPU, for context), that takes around 200-250 ms, and on my dev phone (a Milestone - 600 MHz), it's around 550-950 ms. In both cases, that's fast enough to beat the toast, so - what device, Android version, and Superuser version are you having issues with?

Elaborate on your suggestions? It's not acceptable to wait for the toast to come and go (that's around 4 s latency, which is not at all guaranteed to be consistent), and I don't think people would consider it an improvement if I blacked out the area on which the toast displays (which is also variable among devices).

**Comment by dgw** [comment]
I'm running on a rooted stock LG Optimus V, processor specified at 600MHz, so it's interesting that your 600MHz phone gets it in before the toast. I'm on Android 2.2.1 for now, since I don't want to get into ROMing yet, and running Superuser 2.3.6.3 with su 2.3.2-efgh.

It does feel kind of race condition–y. I've tried a few screenshots and while some have a full toast, some have a faint toast that's just starting to appear. I observed similar problems with other screenshot apps. I have had one screenshot with no discernable toast, but I don't remember which app that was. (I think it was drocap2, but it only happened once.)

I'm sure this problem will be resolved in the future; I'm working on installing su 3.0 beta to go with Superuser Elite, and I think per-app notification settings are either already implemented or on the road map for Elite. But a paid upgrade shouldn't be required to make this work.

Is it possible to grab Superuser rights immediately after the AndroSS service is enabled, rather than waiting until the user grabs a screenshot? I'd be totally fine with having the toast pop up right after I check the "Enabled" box. My only other idea was a configurable delay between screenshot request and fulfillment.

**Comment by tstein** [comment]
> I'm sure this problem will be resolved in the future; I'm working on installing su 3.0 beta to go with Superuser Elite, and I think per-app notification settings are either already implemented or on the road map for Elite. But a paid upgrade shouldn't be required to make this work.

Agreed. While my devices can beat the toast, it's still annoying when I want to take several screenshots in quick succession. I'm not opposed to monetizing software, but basic stuff like su management should be part of the open-source codebase, and this is kind of an obvious feature. Maybe I should get into that next. :P

> Is it possible to grab Superuser rights immediately after the AndroSS service is enabled, rather than waiting until the user grabs a screenshot? I'd be totally fine with having the toast pop up right after I check the "Enabled" box.

Not without some pretty serious re-architecting. When you check the Enabled box, it starts an Android-level service that hangs out, waiting for a trigger. As soon as it gets one, it calls a native method that invokes su to run the binary that actually gets the pixels. Making that binary start immediately and wait for some signal to run would add significant complexity. I've only had a couple reports of issues with that process happening not happening fast enough, and what with hardware advancing the way it does, I'm inclined to stick with it.

> My only other idea was a configurable delay between screenshot request and fulfillment.

I am similarly reluctant. If at all possible, I'd rather make the code faster than add a new code path for a delay. In the spirit of 'measure twice, cut once', could you fire up adb and check logcat for lines from AndroSS with the word 'latency' in them? I'd like to see just how slow it is for you. (Latency refers to the time between when the service receives the trigger and when it gets the pixels back from the native code.) There will also be some other lines of interest in that vicinity starting with "NBridge:".

**Comment by dgw** [comment]
I grabbed a bunch of lines, and tried to pull out the relevant ones. Note that this was a screenshot taken very soon after starting the service ("AndroSS service started", Home, wait 2 seconds, shake-trigger) and that the latency is very high. It isn't consistently that high, but this is the ultimate cold start (I hadn't run AndroSS yet since the last reboot).

```
09-03 17:35:25.723 D/AndroSS ( 3875): Service: Don't know what kind of device we're on...
09-03 17:35:25.723 D/AndroSS ( 3875): Service: This is a regular device.
09-03 17:35:26.913 D/AndroSS ( 3875): Service: Updated output dir to: /sdcard/screenshots/
09-03 17:35:27.033 D/AndroSS ( 3875): NBridge: Executing chmod 770 /data/data/net.tedstein.AndroSS/files/AndroSS
09-03 17:35:27.053 D/AndroSS ( 3875): NBridge: Executing su -c     /data/data/net.tedstein.AndroSS/files/AndroSS
09-03 17:35:27.113 E/su      ( 3885): sudb - Opening database
09-03 17:35:27.113 E/su      ( 3885): sudb - Database opened
09-03 17:35:27.113 E/su      ( 3885): sudb - Database closed
09-03 17:35:27.123 D/su      ( 3885): 10107 /system/bin/sh executing 0 /data/data/net.tedstein.AndroSS/files/AndroSS using shell /system/bin/sh : sh
09-03 17:35:27.143 D/Su.Util (31020): /data/app/com.noshufou.android.su.elite-2.apk
09-03 17:35:27.153 I/ActivityManager(  106): Start proc com.noshufou.android.su.elite for service com.noshufou.android.su.elite/.service.ResultService: pid=3888 uid=10013 gids={3003}
09-03 17:35:27.173 D/AndroSS ( 3887): External: Running in Param mode.
09-03 17:35:27.173 D/AndroSS ( 3875): NBridge: Read 1 bytes from subprocess.
09-03 17:35:27.173 D/AndroSS ( 3875): Service: Got framebuffer params: 320 480 16 0 5 5 6 11 5 0 0 640
09-03 17:35:27.193 D/AndroSS ( 3875): Service: Initialized.
09-03 17:35:27.583 D/dalvikvm( 3875): GC_FOR_MALLOC freed 1799 objects / 351920 bytes in 350ms
09-03 17:35:27.643 D/AndroSS ( 3875): Service: Created.
09-03 17:35:32.853 D/AndroSS ( 3875): Service: Triggering on shake of magnitude 10.438522 with tstamp 225171295142340 (offset: 5595345000).
09-03 17:35:32.863 D/AndroSS ( 3875): Service: Getting framebuffer pixels.
09-03 17:35:32.863 D/AndroSS ( 3875): NBridge: Executing su -c    /data/data/net.tedstein.AndroSS/files/AndroSS
09-03 17:35:33.653 D/AndroSS ( 3903): External: Running in Data mode.
09-03 17:35:33.673 D/AndroSS ( 3903): External: read 307200 bytes from framebuffer.
09-03 17:35:33.673 D/AndroSS ( 3875): NBridge: Converting 153600 pixels.
09-03 17:35:33.683 D/AndroSS ( 3903): External: wrote 307200 bytes.
09-03 17:35:33.893 D/AndroSS ( 3875): NBridge: Conversion finished in 220 ms.
09-03 17:35:34.113 D/AndroSS ( 3875): NBridge: Returning data.
09-03 17:35:34.113 D/AndroSS ( 3875): Service: Creating bitmap.
09-03 17:35:36.023 D/AndroSS ( 3875): Service: Write to /sdcard/screenshots/2011-09-03_17.35.32.png: succeeded
09-03 17:35:37.433 D/AndroSS ( 3875): Service: Screenshot taken in 3155ms (latency: 1250ms, compression: 1717ms).
09-03 17:35:39.243 D/AndroSS ( 3875): Service: Destroyed.
```

_Note: These logs were captured using Log Collector on the phone, not adb. I unfortunately do not presently have a computer I can use for adb work._

**Comment by tstein** [comment]
Well, the good news is that the nature of the problem is obvious.

```
09-03 17:35:32.863 D/AndroSS ( 3875): NBridge: Executing su -c    /data/data/net.tedstein.AndroSS/files/AndroSS
09-03 17:35:33.653 D/AndroSS ( 3903): External: Running in Data mode.
```

For some reason, it's taking 790 ms for the external binary to run after invocation. Nothing heavy is being passed around at that time, so it's strange that it's taking so much more than the 120 ms it did when it was just checking paramters. (That still seems high, but it should be fast enough.) I'll take a close look at similar output from my own devices shortly and see if I can figure out a way to tighten up the code for you.

**Comment by ghost** [comment]
just add a few second delay option, so the user can make sure its on the right screen, cuz shaking my phone sometimes goes to landscape mode ._. 

also maybe add a option to take a screen shot using long search......... im a developer myself so im gonna fork ur repo and try to add it myself =P

**Comment by dgw** [comment]
@zachman1221 Sounds like fun!

@tstein For what it's worth, I will be testing this on a Motorola Triumph once I get around to rooting the one I got last month. Should be a bit more performant. Also, I ended up getting Superuser Elite for the per-app toast setting (among other things), which is why I dropped off of this thread for a while.

**Comment by ghost** [comment]
idk how to build it with the jni/genAndroSSNative.pl

do we need android ndk?

**Comment by tstein** [comment]
@zachman1221 It's not so much a matter of that being difficult as me being a grad student. :) Good luck, but fair warning - I care a lot about code style, so I may mercilessly refactor before accepting anything. If you decide to go after the long-press search, the right way to go about that seems to be pretending to be able to handle [voice commands](http://developer.android.com/reference/android/content/Intent.html#ACTION_VOICE_COMMAND).

@dgw That should be better, though, a while after you filed this issue, I started occasionally getting the problem on my N1 (with a similar processor). The Superuser improvements really screwed me over. ;) Sorry about not having the time to deal with this properly, though.

**Comment by ghost** [comment]
@dgw @tstein It already feels like to much work, idk how to build it anyways..... to test it and make sure it works.....

**Comment by tstein** [comment]
@zachman1221 Don't let that stop you - it's actually not that bad. Just load up the project, go to builders under project properties, pick the native builder, and set the PATH variable in the Environment tab to include wherever you have ndk-build. (Obviously, you need the ndk.)

**Comment by ghost** [comment]
thanks, im on windows... 

i changed the path to were my ndk is it says cannot build the a close button no error info :(

**Comment by tstein** [comment]
Unfortunately, I've no experience with any of this on Windows. The builder runs a Perl script and needs an external binary (base64), so you may need those in some form.

That said, if you aren't going to touch the native code, you may be able to get away with manually running ndk-build just once inside jni/. The purpose of the Perl script is to generate a Java file containing the binary for later retrieval, which, at the time, was the best way I could come up with to sneak it in there.

**Comment by daaave** [comment]
I'm not sure how much help I'm going to be, 'cause I'm sure it's the same root cause and I'm not a developer, but...I'm having the same issue.  The captured toast popup is very light (like it's taking the screen shot just as the popup is fading in or out) but you can tell it's there.  I'm running CyanogenMod 7-06062011-NIGHTLY-N1 on a Google/HTC Nexus One.  Let me know if there's anything I can do to help troubleshoot this issue (if you need output from some kind of system logfile, a pointer to a tutorial on how to get at the log would be great as I've never done it before)!

**Comment by dgw** [comment]
Wow, this is the oldest issue in my GitHub dashboard! I'm going to close this, for these two reasons:

1. Superuser managers nowadays almost universally (in my experience) include an option not to show a toast notification for specific apps, so—assuming AndroSS even still works on current Android phones—that should be a sufficient workaround for this problem.
2. This project has received no updates for over four years, and so this is unlikely to be implemented anyway.
