### ISSUE TITLE
Droid Bionic screenshots are botched

### ISSUE THREAD

**Issue by lament** [tstein/AndroSS#3]
Just rooted my Bionic.

No custom ROM.

http://i.imgur.com/H6hjM.png

**Comment by tstein** [comment]
I've had one other report of corruption like this, but I can't imagine what would cause it. Could you give me the contents of the Debug info screen (under (More) Settings)?

**Comment by lament** [comment]
board: targa
width: 540
height: 960
depth: 32
stride: 2176

red: 8 bits at offset 16
green: 8 bits at offset 8
blue: 8 bits at offset 0
alpha: 8 bits at offset 24

**Comment by tstein** [comment]
Aha - this should be pretty straightforward. 540 px \* 4 B/px = 2160 B. Your stride (the distance between the starts of successive lines) is 2176. I haven't checked, but I bet you that white line is 4px wide in each horizontal stroke. I've been meaning to make this fix, but haven't had a chance - I'm trying to finally finish Tegra support. :) Sorry for the annoyance and thanks for proving this is a relevant issue - this'll be the first big change after that's done.

**Comment by lament** [comment]
Glad I could help. :)

**Comment by tstein** [comment]
I believe I've taken care of this in ccfe74c5f02eb742ae54d57f7576eba3fa9d7528. If you're not in the mood to compile it yourself, [this build](http://dl.dropbox.com/u/9634624/AndroSS/AndroSS_stride.apk) reflects the change. Lemme know if it works - I already have one confirmation that it fixes a similar problem, but I'd like to check that it solves the original issue before pushing. :)

**Comment by lament** [comment]
I did an OTA update which got rid of root, and I have a Galaxy Nexus on the way and selling the Bionic so I won't be rooting it to test. Sorry!

**Comment by tstein** [comment]
Good choice - ICS is fantastic. :) Thanks anyway.
